fundacion/applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/',
        views.EntradaListView.as_view(),
        name='lista-entradas',
    ),
    path(
        'entradas/<slug>',
        views.EntradaDetailView.as_view(),
        name='edit-entradas',
    ),

]

fundacion/applications/esal/urls.py
from django.urls import path
from . import views

app_name = "esal_app"

urlpatterns = [
    path(
        'esal/',
        views.EsalListView.as_view(),
        name='listado-esal',
    ),
    path(
        'CreateEsal/',
        views.EsalCreateView.as_view(),
        name='create-esal',
    ),

]

fundacion/applications/home/urls.py
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        '',
        views.homePageView.as_view(),
        name='index',
    ),
    path(
        'suscribirme',
        views.SuscribeCreateView.as_view(),
        name='home_suscribe',
    ),
    path(
        'contacto',
        views.ContactoCreateView.as_view(),
        name='home-contacto',
    ),
]

fundacion/applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'create/',
        views.UserCreateView.as_view(),
        name='user-create'
    ),
    path(
        'login/',
        views.LoginUsers.as_view(),
        name='user-login',
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'PassUpdate/',
        views.UpdatePasswordView.as_view(),
        name='user-UpdatePassword',
    ),
    path(
        'lista/',
        views.UserListView.as_view(),
        name='user-listado',
    ),
    path(
        'users/update/<pk>/',
        views.UserUpdateView.as_view(),
        name='user-update',
    ),
    path(
        'users/delete/<pk>/',
        views.UserDeleteView.as_view(),
        name='user-delete',
    ),
]

fundacion/fundacion/urls.py
"""fundacion URL Configuration
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve

from django.conf.urls import handler404, handler500

from applications.home.views import Error404View, Error500View

urlpatterns = (
    [
        path('admin/', admin.site.urls),

        re_path('', include('applications.home.urls')),
        re_path('', include('applications.users.urls')),
        re_path('', include('applications.entrada.urls')),
        re_path('', include('applications.favoritos.urls')),
        re_path('', include('applications.esal.urls')),

        # urls para ckeditor para
        re_path(r'^ckeditor/', include("ckeditor_uploader.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# PARA QUE FUNCINE LAS MEDIAS CUNADO SE ESTAN CONSULTANDO EN LA PAGINA 

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT
    })
]

handler404 = Error404View.as_view()
handler500 = Error500View.as_error_view()

fundacion/templates/includes/footer.html
<footer>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 col-md-4">
                <h3 class="text-center">Sobre Cristo Redentor</h3>
                <p class="text-justify">La Fundación Cristo Redentor les agradece, por la participación en la
                    suscripción al canal de youtube, gran actividad en la redes sociales en procura de una vida
                    saludable a nuestros
                    adultos mayores. </p>
            </div>
            <div class="col-xs-12 col-md-5">
                <a align="left" href="{% url 'home_app:index' %}"><img src="/static/img/logo_funda.png" alt=""
                        style="width: 360px; height: 160px;"> </a>
            </div>
            <div class="col-xs-12 col-md-3">
                <div class="col-xs-12">
                    <h4>Contactenos</h4>
                </div>
                <h5>+573187345801</h5>
                <h5>secretaria@fundacioncristoredentor.org</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <p class="text-center">© 2022 FUNDACIÓN CRISTO REDENTOR - Todos los derechos reservados</p>
            </div>
        </div>
    </div>
</footer>

fundacion/templates/includes/header.html
<header>

    <nav class="navbar navbar-expand-sm navbar-dark bg-info" style="font-size: 24px;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home_app:index' %}">
                <img src="/static/img/logo_funda.png" alt="" width="200">FUNDACIÓN CRISTO REDENTOR
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="False"
                aria-label="Toogle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse flex-row-reverse" id="navbarSupportedContent">
                <ul class="navbar-nav ">
                    <li class="nav-item"><a class="nav-link" href="{% url 'home_app:index' %}">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link"
                            href="{% url 'entrada_app:lista-entradas' %}">Actividades</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Inicio</a></li>

                    {% if not user.is_anonymous %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">Fundación</a>
                        <ul class="dropdown-menu ">
                            <li><a class="dropdown-item" href="{% url 'users_app:user-create' %}">Crear
                                    login</a></li>
                            <li><a class="dropdown-item" href="{% url 'users_app:user-UpdatePassword' %}">Password</a>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'users_app:user-listado' %}">listado</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'esal_app:listado-esal' %}">Esal</a></li>
                    </li>
                </ul>
                </li>
                {% else %}
                {% endif %}
                <li>
                    {% if not user.is_anonymous %}
                    {% else %}
                    <a type="button" class="btn btn-success" href="{% url 'users_app:user-login' %}">Acceder</a>
                    {% endif %}
                </li>
                <li>
                    {% if user.is_authenticated %}
                    <a type="button" class="btn btn-secondary" href="{% url 'users_app:user-logout' %}">Salir</a>
                    {% else %}
                    {% endif %}
                </li>
                </ul>
            </div>
        </div>
    </nav>

</header>