fundacion/applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/',
        views.EntradaListView.as_view(),
        name='lista-entradas',
    ),
    path(
        'entradas/<slug>',
        views.EntradaDetailView.as_view(),
        name='edit-entradas',
    ),

]

fundacion/applications/favoritos/urls.py
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil/',
        views.UserPageView.as_view(),
        name='favorito-user',
    ),
    path(
        'agregar-entrada/<pk>',
        views.AgregarFavoritosView.as_view(),
        name='agregar-favoritos',
    ),
    path(
        'delete-favorito/<pk>',
        views.FavoritosDeleteView.as_view(),
        name='delete-favoritos',
    ),
]

fundacion/fundacion/urls.py
"""fundacion URL Configuration
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve

from django.conf.urls import handler404, handler500

from applications.home.views import Error404View, Error500View

urlpatterns = (
    [
        path('admin/', admin.site.urls),

        re_path('', include('applications.home.urls')),
        re_path('', include('applications.users.urls')),
        re_path('', include('applications.entrada.urls')),
        re_path('', include('applications.favoritos.urls')),
        re_path('', include('applications.esal.urls')),

        # urls para ckeditor para
        re_path(r'^ckeditor/', include("ckeditor_uploader.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# PARA QUE FUNCINE LAS MEDIAS CUNADO SE ESTAN CONSULTANDO EN LA PAGINA 

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT
    })
]

handler404 = Error404View.as_view()
handler500 = Error500View.as_error_view()

fundacion/applications/entrada/models.py
# librerias de python
from datetime import timedelta, datetime

from django.conf import settings
from django.db import models
from django.db.models.signals import post_save

from django.template.defaultfilters import slugify

# terceros
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField
from PIL import Image

# managers
from .managers import EntradaManager

# Create your models here.


class Categoria(TimeStampedModel):
    short_name = models.CharField('Nombre corto', max_length=15, unique=True)
    name = models.CharField('Nombre', max_length=30)

    class Meta:
        verbose_name = ('Categoria')
        verbose_name_plural = ('Categorias')

    def __str__(self):
        return self.name


class Tag(TimeStampedModel):
    """Etiquetas de un articulo"""

    name = models.CharField('Nombre', max_length=30)

    class Meta:
        verbose_name = ('Tag')
        verbose_name_plural = ('Tags')

    def __str__(self):
        return self.name


class Entrada(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    titulo = models.CharField('Titulo', max_length=200)
    resumen = models.TextField('resumen')
    contenido = RichTextUploadingField('Contenido')
    publicar = models.BooleanField(default=False)
    image = models.ImageField('Imagen', upload_to='Entrada',)
    portada = models.BooleanField(default=False)
    in_home = models.BooleanField(default=False)
    carousel = models.BooleanField(default=False)
    # para las paginas de url automaticas
    slug = models.SlugField(editable=False, max_length=300)

    objects = EntradaManager()

    class Meta:
        verbose_name = ('Entrada')
        verbose_name_plural = ('Entradas')

    def __str__(self):
        return self.titulo + ' - ' + str(self.in_home) + ' - ' + str(self.portada) + ' - ' + str(self.publicar)


# procedimiento para crear la urls automaticas para CEO de la pagina


    def save(self, *args, **kwargs):
        now = datetime.now()
        total_time = timedelta(
            hours=now.hour,
            minutes=now.minute,
            seconds=now.second
        )
        seconds = int(total_time.total_seconds())
        slug_unique = '%s %s' % (self.titulo, str(seconds))

        self.slug = slugify(slug_unique)

        super(Entrada, self).save(*args, **kwargs)


def optimizar_imagen(sender, instance, **kwargs):

    if instance.image:
        image = Image.open(instance.image.path)
        image.save(instance.image.path, quality=20, optimize=True)


post_save.connect(optimizar_imagen, sender=Entrada)

fundacion/applications/entrada/views.py
from django.shortcuts import render

# Create your views here.


from django.views.generic import (
    DetailView,
    ListView,

)

from .models import Entrada, Categoria


class EntradaListView(ListView):
    template_name = 'entrada/lista_entrada.html'
    context_object_name = 'entradas'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super(EntradaListView, self).get_context_data(**kwargs)
        context["Categorias"] = Categoria.objects.all()
        return context

    def get_queryset(self):
        buscarentrada = self.request.GET.get("buscarentrada", '')
        categoria = self.request.GET.get("categoria", '')
        resultado = Entrada.objects.Buscar_entradas(
            buscarentrada, categoria)
        return resultado


class EntradaDetailView(DetailView):
    template_name = "entrada/detail.html"
    model = Entrada

fundacion/templates/entrada/base_entrada.html
{% extends "panel.html" %}

{% load static %}

{% block css %}

{% endblock css %}


{% block panel %}

<!-- contenido html cada pagina  -->


{% endblock panel %}

{% block js %}

{% endblock js %}

fundacion/templates/entrada/detail.html
<!-- head para PC -->
{% extends "entrada/base_entrada.html" %}
{% load static %}

{% block panel %}

<div class="container-fluid">
    <h3 class="cell">{{entrada.titulo}}</h3>
    <div class="row">
        <div class=" callout col-8">
            <h3>Resumen:</h3>
            <p class="text-justify">{{entrada.resumen}}</p>
        </div>
        <div class="col-8">
            <p class="text-justify">{{entrada.contenido | safe}}</p>
        </div>
        <div class="col-4">
            <div class="card" style="width: 100%;">
                <img src="{{entrada.image.url}}">
                <div class="card-section" style="width: 100%;">
                    <form class="" method="post" action="{% url 'favoritos_app:agregar-favoritos' entrada.id %}">
                        {% csrf_token %}
                        <button class="btn col-12 btn-outline-danger" type="submit">Agregar a Favoritos </button>
                    </form>
                    <hr class="dropdown-divider">
                    <div class="margin-top: 2em">
                        <a href="{% url 'entrada_app:lista-entradas' %}"
                            class="btn col-12 btn-outline-secondary">Regresar a
                            las Entradas</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock panel %}

fundacion/templates/entrada/lista_entrada.html
<!-- head para PC -->
{% extends "entrada/base_entrada.html" %}
{% load static %}

{% block panel %}


<div class="container-fluid">
    <div class="row justify-content-center">

        <div class="col-xs-12 col-md-10 ">

            <!-- Inicio del Bucador por categorias -->
            <div class="col-xs-12 col-md-10" style="margin-top: 1em;">
                <form class="input-group" method="GET"> {% csrf_token %}
                    <input class="input-group-field" type="text" id="buscarentrada" name="buscarentrada"
                        placeholder="Buscar ...">
                    <div class="input-group-button">
                        <input type="submit" class="button" value="Buscar">
                    </div>
                </form>
            </div>

            <!-- Lista de Actividades realizadas  -->

            <div class="row col-xs-12 col-md-10" style="width: 100%;">
                {% for entrada in entradas %}
                <div class="col-xs-12 col-md-4 ">
                    <div class="card" style="width: 100%;">
                        <img src="{{entrada.image.url}}" style="height: 200px">
                        <div class="card-section">
                            <a href="{% url 'entrada_app:edit-entradas' entrada.slug %}">
                                <h4>{{entrada.titulo | truncatechars:40}}</h4>
                            </a>
                            <p>{{entrada.resumen | truncatechars:70}}</p>
                        </div>
                    </div>
                </div>

                {% empty %}

                <h3 style="color:red">No se encontraron resultados para la consulta </h3>

                {% endfor %}
            </div>
            <!-- Fin de lista de actividades realizadas -->

        </div>

        <!-- Listado de Categorias del sistemas -->
        <div class="col-xs-12 col-md-2">
            <div class="col-xs-12 col-md-12">
                <h4>Categorias:</h4>
                <ul class="nav flex-column">
                    {% for categoria in Categorias %}
                    <li><a href="?categoria={{categoria.short_name}}">{{categoria.name}}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <!-- Inicio de la Paginacion de las actividades realizadas -->

    <div class="row">
        <nav>
            <ul class="pagination">
                <li>
                    {% if page_obj.has_previous %}
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                    {% endif %}
                </li>
                <li class="page-item">
                    <a class="page-link"> Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</a>
                </li>

                <li>
                    {% if page_obj.has_next %}
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                    {% endif %}
                </li>

            </ul>
        </nav>
    </div>



</div>



{% endblock panel %}

fundacion/templates/entrada/paginate.html
<div class="cell">
    {% if is_paginated %}
    <nav aria-label="Pagination">
        <ul class="Pagination">
            {% if page_obj.has_previous %}
            <li class="Pagination-previous">
                <a href="?page={{page_obj.previous_page_number}}">Atras</a>
            </li>
            {% endif %}

            {% for pagina in paginator.page_range %}

            {% ifequal pagina page_obj.number %}
            <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }} </li>
            {% else %}
            <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>

            {% endifequal %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="pagination-next">
                <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}