fundacion/applications/home/urls.py
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        '',
        views.homePageView.as_view(),
        name='index',
    ),
    path(
        'suscribirme',
        views.SuscribeCreateView.as_view(),
        name='home_suscribe',
    ),
    path(
        'contacto',
        views.ContactoCreateView.as_view(),
        name='home-contacto',
    ),
]

fundacion/applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'create/',
        views.UserCreateView.as_view(),
        name='user-create'
    ),
    path(
        'login/',
        views.LoginUsers.as_view(),
        name='user-login',
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'PassUpdate/',
        views.UpdatePasswordView.as_view(),
        name='user-UpdatePassword',
    ),
    path(
        'lista/',
        views.UserListView.as_view(),
        name='user-listado',
    ),
    path(
        'users/update/<pk>/',
        views.UserUpdateView.as_view(),
        name='user-update',
    ),
    path(
        'users/delete/<pk>/',
        views.UserDeleteView.as_view(),
        name='user-delete',
    ),
]

fundacion/fundacion/urls.py
"""fundacion URL Configuration
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve

from django.conf.urls import handler404, handler500

from applications.home.views import Error404View, Error500View

urlpatterns = (
    [
        path('admin/', admin.site.urls),

        re_path('', include('applications.home.urls')),
        re_path('', include('applications.users.urls')),
        re_path('', include('applications.entrada.urls')),
        re_path('', include('applications.favoritos.urls')),
        re_path('', include('applications.esal.urls')),

        # urls para ckeditor para
        re_path(r'^ckeditor/', include("ckeditor_uploader.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# PARA QUE FUNCINE LAS MEDIAS CUNADO SE ESTAN CONSULTANDO EN LA PAGINA 

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT
    })
]

handler404 = Error404View.as_view()
handler500 = Error500View.as_error_view()

fundacion/applications/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

# Managers locales
from .managers import UserManager

# Create your models here.


class User(AbstractBaseUser, PermissionsMixin):

    # TIPOS DE USUARIOS
    ADMINISTRADOR = '0'
    SECRETARIA = '1'
    TESORERO = '2'
    GERENTE = '3'
    JUNTA = '4'

    # GENEROS
    HOMBRE = 'M'
    MUJER = 'F'
    OTRO = 'O'

    OCUPATION_CHOICES = [
        (ADMINISTRADOR, 'Administrador'),
        (SECRETARIA, 'Secretario/a'),
        (TESORERO, 'Tesorero'),
        (GERENTE, 'Gerente'),
        (JUNTA, 'Junta'),
    ]

    GENDER_CHOICES = [
        (HOMBRE, 'Masculino'),
        (MUJER, 'Femenino'),
        (OTRO, 'Otros'),
    ]

    username = models.CharField(max_length=15, unique=True)
    email = models.EmailField()
    nombres = models.CharField(max_length=30, blank=True)
    apellidos = models.CharField(max_length=30, blank=True)
    genero = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    ocupation = models.CharField(
        max_length=1, choices=OCUPATION_CHOICES, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return self.nombres + ' ' + self.apellidos

fundacion/applications/users/forms.py
from pyexpat import model
from django import forms
from django.contrib.auth import authenticate

from .models import User


class UserCreateForm(forms.ModelForm):

    password1 = forms.CharField(
        label=("Contraseña"),
        required=True,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control-lg',
                   'placeholder': 'Contraseña'
                   }
        )
    )

    password2 = forms.CharField(
        label=("Contraseña"),
        required=True,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control-lg',
                   'placeholder': 'Repetir Contraseña'
                   }
        )
    )

    class Meta:

        model = User
        fields = (
            'username',
            'email',
            'nombres',
            'apellidos',
            'genero',
            'ocupation'
        )
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Usuario', 'class': 'form-control-lg'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Correo Electronico', 'class': 'form-control-lg'}),
            'Nombres': forms.TextInput(attrs={'placeholder': 'Nombres', 'class': 'form-control-lg'}),
            'Apellidos': forms.TextInput(attrs={'placeholder': 'Apellidos', 'class': 'form-control-lg'}),
            'Genero': forms.Select(attrs={'placeholder': 'Genero', 'class': 'form-select-lg'}),
            'ocupation': forms.Select(attrs={'placeholder': 'Ocupación', 'class': 'form-select-lg'}),

        }

    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error(
                'password2', 'Las contraseñas no son identicas verificar')


class LoginForm(forms.Form):
    username = forms.CharField(
        label="username",
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'username',
                'class': 'form-control-lg',
            }
        )
    )
    password = forms.CharField(
        label="password",
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña',
                'class': 'form-control-lg',
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not authenticate(username=username, password=password):
            raise forms.ValidationError('Los datos de usuarios no correctos')

        return self.cleaned_data


class UpdatePasswordForm(forms.Form):
    password1 = forms.CharField(
        label=("Contraseña"),
        required=True,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control-lg',
                   'placeholder': 'Contraseña Actual '
                   }
        )
    )

    password2 = forms.CharField(
        label=("Contraseña"),
        required=True,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control-lg',
                   'placeholder': 'Contraseña Nueva '
                   }
        )
    )

class UserUpdateForm(forms.ModelForm):

    class Meta:

        model = User
        fields = (
            'email',
            'nombres',
            'apellidos',
            'genero',
            'ocupation',
            'is_active',
        )
        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'Correo Electronico', 'class': 'form-control-lg'}),
            'Nombres': forms.TextInput(attrs={'placeholder': 'Nombres', 'class': 'form-control-lg'}),
            'Apellidos': forms.TextInput(attrs={'placeholder': 'Apellidos', 'class': 'form-control-lg'}),
            'Genero': forms.Select(attrs={'placeholder': 'Genero', 'class': 'form-select'}),
            'ocupation': forms.Select(attrs={'placeholder': 'Ocupación', 'class': 'form-select'}),
            'is_active': forms.CheckboxInput(attrs={'type': 'checkbox', 'class': 'form-check-input'})

        }

fundacion/applications/users/views.py
import datetime

from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
# Create your views here.

from django.views.generic import (
    View,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)

from django.views.generic.edit import (
    FormView,
)

from .forms import (
    UserCreateForm,
    LoginForm,
    UpdatePasswordForm,
    UserUpdateForm,
)

from applications.users.mixins import (
    AdminpermisoMixin
)

from .models import User


class FechaMixin(object):
    def get_context_data(self, **kwargs):
        context = super(FechaMixin, self).get_context_data(**kwargs)
        context['fecha'] = datetime.datetime.now()
        return context

# DESARROLLO DE LOS DIFERENTES VIEWS


class UserCreateView(LoginRequiredMixin, FechaMixin, FormView):
    template_name = 'users/create.html'
    form_class = UserCreateForm
    success_url = reverse_lazy('home_app:index')
    login_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        #
        User.objects.create_user(
            form.cleaned_data['username'],
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            nombres=form.cleaned_data['nombres'],
            apellidos=form.cleaned_data['apellidos'],
            genero=form.cleaned_data['genero'],
            ocupation=form.cleaned_data['ocupation'],
        )
        #
        return super(UserCreateView, self).form_valid(form)


class LoginUsers(FechaMixin, FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('home_app:index')

    def form_valid(self, form):
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUsers, self).form_valid(form)


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )


class UserListView(AdminpermisoMixin, FechaMixin, ListView):
    template_name = 'users/lista.html'
    context_object_name = 'usuarios'
    login_url = reverse_lazy('users_app:user-login')

    def get_queryset(self):
        return User.objects.usuarios_sistema()


# ACTUALIZACION EN FORMULARIOS DE USUARIOS


class UpdatePasswordView(LoginRequiredMixin, FechaMixin, FormView):
    template_name = 'users/UpdateLogin.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        usuario = self.request.user
        user = authenticate(
            username=usuario.username,
            password=form.cleaned_data['password1']
        )
        if user:
            new_password = form.cleaned_data['password2']
            usuario.set_password(new_password)
            usuario.save()

        logout(self.request)
        return super(UpdatePasswordView, self).form_valid(form)


# ACUTLIZAR EL USUARIO


class UserUpdateView(UpdateView):
    template_name = 'users/update.html'
    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy('users_app:user-listado')


class UserDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('users_app:user-listado')

fundacion/templates/users/UpdateLogin.html
{% extends "users/base_users.html" %}
{% load static %}

{% block title %} Actualizar Usuarios {% endblock %}

{% block content %}

{% include "includes/header.html" %}

<div class="container-fluid">

    <div class="row justify-content-center">
        <div class="col-xs-12 col-md-8 align-center">
            <div class="col-xs-12 col-md-8" style="margin-top: 2em;">
                <div class="card" style="width: 100%;">
                    <div class="card-header">
                        <h4>Cambiar la Contraseña de: {{user.get_full_name}}</h4>
                    </div>
                    <div class="card-body">
                        <div class="row justify-content-center">
                            <form class="col-xs-12 col-md-12 " method="post">{% csrf_token%}
                                <div class="col-xs-12 col-md-12">

                                    <div class="form-control">{{form.as_p}}</div>
                                </div>
                                <br>

                                <button type="submit" class="col-12 btn btn-outline-success">Actualizar
                                    contraseña</button>

                            </form>
                        </div>
                        <br>
                        <p>La fecha: {{fecha}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

fundacion/templates/users/base_users.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myweb.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

fundacion/templates/users/create.html
<!-- head para PC -->
{% extends "users/base_users.html" %}
{% load static %}

{% block title %} Crear Usuarios {% endblock %}

{% block content %}

{% include "includes/header.html" %}

<div class="container-fluid" style="margin-top: 2em;">
    <div class="row justify-content-center">
        <div class="col-xs-12 col-md-6">
            <div class="card " style="width: 100%;">
                <div class="card-header">
                    <h4 class="text-center">INGRESE DATOS DEL USUARIO</h4>
                </div>
                <br>
                <div class="card-body">
                    <form class="col-xs-12 col-md-12" method="post" enctype="multipart/form-data"> {% csrf_token%}

                        <div class="row">
                            <div class="mb-3 col-xs-12 col-md-4">
                                <label>Usuario:</label>
                                <div class="input-group form-control">
                                    {{form.username}}
                                </div>
                            </div>
                            <div class="mb-3 col-xs-12 col-md-8">
                                <label>Correo:</label>
                                <div class="form-control">
                                    {{form.email}}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class=" mb-3 col-md-6">
                                <label>Nombres:</label>
                                <div class="form-control">
                                    {{form.nombres}}
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6">
                                <label>Apellidos: </label>
                                <div class="form-control">{{form.apellidos}} </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-3 col-xs-12 col-md-6">
                                <label>Genero:</label>
                                <div class="form-control">{{form.genero}}</div>
                            </div>
                            <div class=" mb-3 col-xs-12 col-md-6">
                                <label>Permiso:</label>
                                <div class="form-control">{{form.ocupation}}</div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-3 col-xs-12 col-md-6">
                                <label>Contraseña: </label>
                                <div class="form-control">{{form.password1}}</div>

                            </div>
                            <div class="mb-3 col-xs-12 col-md-6">
                                <label>Repetir Contraseña:</label>
                                <div class="form-control">{{form.password2}}</div>

                                {% for e in form.password2.errors %}
                                <p class="alert alert-danger" role="alert">{{e}}</p>
                                {% endfor %}
                            </div>
                        </div>

                        <button type="submit" class=" col-12 btn btn-outline-success">Registrar</button>
                    </form>
                    <hr class="dropdown-divider">
                    <div class="col-12 margin-top: 2em">
                        <a href="{% url 'users_app:user-listado' %}" class="btn col-12 btn-outline-secondary">Regresar
                            al
                            Listado</a>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

fundacion/templates/users/lista.html
{% extends "users/base_users.html" %}
{% load static %}

{% block title %} Listado de Usuarios del sistema {% endblock %}

{% block content %}

{% include "includes/header.html" %}

<div class="container-fluid">
    <section class="altura">
        <div class="row col-xs-12 col-md-12">
            <div class="col-xs-12 col-md-12 align-center ">
                <h3 class="col" style="margin-bottom: 1em; text-align: center;">Usuarios del Sistema </h3>
                <h4 class=" col color_fecha">Fecha: {{fecha}}</h4>

                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Email</th>
                            <th scope="col">Nombres</th>
                            <th scope="col">Apellidos</th>
                            <th scope="col">Ultima Conexion</th>
                            <th scope="col">Permisos</th>
                            <th scope="col">Estado</th>
                            <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for usuario in usuarios %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{ usuario.email }}</td>
                            <td>{{ usuario.nombres }}</td>
                            <td>{{ usuario.apellidos}}</td>
                            <td>{{ usuario.last_login }}</td>
                            <td>{{ usuario.get_ocupation_display }}</td>
                            <td>
                                {% if usuario.is_active %}
                                <span class="label success">Activo</span>
                                {% else %}
                                <span class="label alert">Inactivo</span>
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'users_app:user-update' usuario.pk %}"
                                    class="btn btn-outline-warning">Actualizar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="row col-xs-12 col-md-12">
                    <div class="col-xs-12 col-md-6"><a href="{% url 'users_app:user-create' %}"
                            class="col-12 btn btn-outline-success">Agregar Usuario</a></div>
                    <br>
                    <div class="col-xs-12 col-md-6"><a href="{% url 'home_app:index' %}"
                            class="col-12 btn btn-outline-secondary">Inicio</a></div>
                </div>
            </div>
        </div>

    </section>
</div>

{% endblock content %}

fundacion/templates/users/login.html
{% extends "users/base_users.html" %}
{% load static %}

{% block title %} Ingresar {% endblock %}

{% block content %}

{% include "includes/header.html" %}

<div class="container-fluid" style="margin-top:2em;">
    <div class="row justify-content-center">
        <div class="col-xs-12 col-md-6">
            <div class="card" style="width: 100%;">
                <div class="card-divider">
                    <h4 class="text-center">ACCESO DE USUARIO</h4>
                </div>
                <div class="car-section">
                    <form class="col-xs-12 col-md-12 " method="post" enctype="multipart/form-data">{% csrf_token %}

                        <div class="row justify-content-center">
                            <div class=" mb-3 col-xs-12 col-md-7">
                                <label>Usuario:</label>
                                <div class="form-control-lg">{{form.username}}</div>
                            </div>
                            <div class="mb-3 col-xs-12 col-md-7">
                                <label>Contraseña: </label>
                                <div class="form-control-lg">{{form.password}}</div>
                            </div>
                        </div>
                        <br>
                        <button type="submit" class="col-12 btn btn-outline-success">Acceder</button>
                    </form>
                    <br>
                    <a class="col-12 btn btn-outline-secondary" href="{% url 'users_app:user-create' %}">Registrar</a>
                </div>
            </div>
        </div>

    </div>

</div>


{% endblock content %}

fundacion/templates/users/update.html
{% extends "users/base_users.html" %}
{% load static %}

{% block title %} Actualizar usuarios {% endblock %}

{% block content %}

{% include "includes/header.html" %}

<div class="container-fluid" style="margin-top:2em;">
    <div class="row justify-content-center">
        <div class="col-xs-12 col-md-6">
            <div class="card" style="width: 100%;">
                <div class="card-divider">
                    <h4>Datos del usuario para actualizar</h4>
                </div>
                <div class="card-section">

                    <form class="col-xs-12 col-md-12" method="POST">{% csrf_token %}

                        <div class="col-xs-12 col-md-12">
                            <label>Email:</label>
                            <div class="form-control">
                                {{ form.email }}
                            </div>
                            {% for error in form.email.errors %}
                            <p class="col" style="color: red;">
                                {{ error|escape }}
                            </p>
                            {% endfor %}
                        </div>

                        <div class="row">
                            <div class="col-xs-12 col-md-6">
                                <label>Nombres:</label>
                                <div class="controls">
                                    {{form.nombres}}
                                </div>
                            </div>

                            <div class="col-xs-12 col-md-6">
                                <label>Apellidos:</label>
                                <div class="controls">
                                    {{form.apellidos}}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-12 col-md-6">
                                <label>Permisos:</label>
                                <div class="form-control">
                                    {{form.ocupation}}
                                </div>
                            </div>

                            <div class="col-xs-12 col-md-6">
                                <label>Genero:</label>
                                <div class="form-control">
                                    {{form.genero}}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-12 col-md-6">
                                <label>Usuario Activo:</label>
                                <div class="form-control">
                                    {{ form.is_active }}
                                </div>
                            </div>
                        </div>
                        <hr>

                        <div>
                            <button type="submit" class="btn btn-outline-success col-12">Guardar</button>
                        </div>
                        <br>
                    </form>
                    <form action="{% url 'users_app:user-delete' object.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger col-12">Eliminar</button>
                    </form>

                </div>

            </div>
        </div>

    </div>
</div>

{% endblock content %}