fundacion/applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/',
        views.EntradaListView.as_view(),
        name='lista-entradas',
    ),
    path(
        'entradas/<slug>',
        views.EntradaDetailView.as_view(),
        name='edit-entradas',
    ),

]

fundacion/applications/favoritos/urls.py
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil/',
        views.UserPageView.as_view(),
        name='favorito-user',
    ),
    path(
        'agregar-entrada/<pk>',
        views.AgregarFavoritosView.as_view(),
        name='agregar-favoritos',
    ),
    path(
        'delete-favorito/<pk>',
        views.FavoritosDeleteView.as_view(),
        name='delete-favoritos',
    ),
]

fundacion/applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'create/',
        views.UserCreateView.as_view(),
        name='user-create'
    ),
    path(
        'login/',
        views.LoginUsers.as_view(),
        name='user-login',
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'PassUpdate/',
        views.UpdatePasswordView.as_view(),
        name='user-UpdatePassword',
    ),
    path(
        'lista/',
        views.UserListView.as_view(),
        name='user-listado',
    ),
    path(
        'users/update/<pk>/',
        views.UserUpdateView.as_view(),
        name='user-update',
    ),
    path(
        'users/delete/<pk>/',
        views.UserDeleteView.as_view(),
        name='user-delete',
    ),
]

fundacion/fundacion/urls.py
"""fundacion URL Configuration
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve

from django.conf.urls import handler404, handler500

from applications.home.views import Error404View, Error500View

urlpatterns = (
    [
        path('admin/', admin.site.urls),

        re_path('', include('applications.home.urls')),
        re_path('', include('applications.users.urls')),
        re_path('', include('applications.entrada.urls')),
        re_path('', include('applications.favoritos.urls')),
        re_path('', include('applications.esal.urls')),

        # urls para ckeditor para
        re_path(r'^ckeditor/', include("ckeditor_uploader.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# PARA QUE FUNCINE LAS MEDIAS CUNADO SE ESTAN CONSULTANDO EN LA PAGINA 

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT
    })
]

handler404 = Error404View.as_view()
handler500 = Error500View.as_error_view()

fundacion/applications/favoritos/models.py
from django.db import models
from django.conf import settings

# Create your models here.

# managers
from .managers import FovoritosManager


from model_utils.models import TimeStampedModel

from applications.entrada.models import Entrada


class Favoritos(TimeStampedModel):
    """Favoritos"""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='user_favoritos', on_delete=models.CASCADE)
    entrada = models.ForeignKey(
        Entrada, related_name='entradas_favoritas', on_delete=models.CASCADE)

    objects = FovoritosManager()

    class Meta:
        unique_together = ('user', 'entrada')
        verbose_name = ("Favoritos")
        verbose_name_plural = ("Favoritos")

    def __str__(self):
        return self.entrada.titulo

fundacion/applications/favoritos/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse

from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
from django.views.generic import (
    ListView,
    View,
    DeleteView
)

from applications.entrada.models import Entrada

from .models import Favoritos


class UserPageView(LoginRequiredMixin, ListView):
    template_name = "favoritos/perfil.html"
    context_object_name = 'entradas_user'
    login_url = reverse_lazy('users_app:user-login')

    def get_queryset(self):
        return Favoritos.objects.entradas_user(self.request.user)


class AgregarFavoritosView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users_app:user-login')

    def post(self, request, *args, **kwargs):
        usuario = self.request.user
        entrada = Entrada.objects.get(id=self.kwargs['pk'])
        Favoritos.objects.create(
            user=usuario,
            entrada=entrada,
        )
        return HttpResponseRedirect(
            reverse(
                'favoritos_app:favorito-user'
            )
        )


class FavoritosDeleteView(DeleteView):
    model = Favoritos
    success_url = reverse_lazy('favoritos_app:favorito-user')

fundacion/templates/favoritos/base_favoritos.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myfundacion.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

fundacion/templates/favoritos/perfil.html
<!-- head para PC -->
{% extends "favoritos/base_favoritos.html" %}
{% load static %}

{% block title %} Actividades Favoritas {% endblock %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center" style="margin-top: 1em;">
        <!-- bloque de datos de usuario -->
        <div class="cell small-12 large-4">
            <div class="callout">
                <h4>usuario: <span>{{user.username}}</span></h4>
                <h5>{{user.get_full_name}}</h5>
                <p>{{user.email}} - </p>
                <a href="{% url 'users_app:user-logout'%}">Salir</a>

            </div>
        </div>
        <!-- FIN bloque de datos de usuario -->


        <!-- bloque de articulos favoritos de usuario -->
        <div class="cell large-8 grid-x grid-margin-x align-center">

            {% for entradas in entradas_user %}

            <div class="cell small-12">
                <div class="card-favoritos">
                    <img class="card-favoritos-img" src="{{entradas.entrada.image.url}}">
                    <div class="card-favoritos-body">
                        <h3 class="card-favoritos-body-titulo">{{entradas.entrada.titulo}}</h3>
                        <p class="card-favoritos-body-text">{{entradas.entrada.resumen}}</p>
                        <form class="card-favoritos-body-actions" method="post"
                            action="{% url 'favoritos_app:delete-favoritos' entradas.id %}"> {% csrf_token %}
                            <a class="button warning"
                                href="{% url 'entrada_app:edit-entradas' entradas.entrada.id %}">Ver</a>

                            <button type="submit" class="button alert">Eliminar</button>
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
        <!-- FIN bloque de articulos favoritos de usuario -->
    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}